mkdir 1-SmileyPeoples\face-positive
mkdir 1-SmileyPeoples\face-neutral
mkdir 1-SmileyPeoples\face-negative
mkdir 1-SmileyPeoples\face-sick
mkdir 1-SmileyPeoples\face-role
mkdir 1-SmileyPeoples\face-fantasy
mkdir 1-SmileyPeoples\cat-face
mkdir 1-SmileyPeoples\monkey-face
mkdir 1-SmileyPeoples\person
mkdir 1-SmileyPeoples\person-role
mkdir 1-SmileyPeoples\person-fantasy
mkdir 1-SmileyPeoples\person-gesture
mkdir 1-SmileyPeoples\person-activity
mkdir 1-SmileyPeoples\person-sport
mkdir 1-SmileyPeoples\family
mkdir 1-SmileyPeoples\body
mkdir 1-SmileyPeoples\emotion
mkdir 1-SmileyPeoples\clothing
mkdir 2-AnimalsNature\animal-mammal
mkdir 2-AnimalsNature\animal-bird
mkdir 2-AnimalsNature\animal-amphibian
mkdir 2-AnimalsNature\animal-reptile
mkdir 2-AnimalsNature\animal-marine
mkdir 2-AnimalsNature\animal-bug
mkdir 2-AnimalsNature\plant-flower
mkdir 2-AnimalsNature\plant-other
mkdir 3-FoodDrink\food-fruit
mkdir 3-FoodDrink\food-vegetable
mkdir 3-FoodDrink\food-prepared
mkdir 3-FoodDrink\food-asian
mkdir 3-FoodDrink\food-sweet
mkdir 3-FoodDrink\drink
mkdir 3-FoodDrink\dishware
mkdir 4-TravelPlaces\place-map
mkdir 4-TravelPlaces\place-geographic
mkdir 4-TravelPlaces\place-building
mkdir 4-TravelPlaces\place-religious
mkdir 4-TravelPlaces\place-other
mkdir 4-TravelPlaces\transport-ground
mkdir 4-TravelPlaces\transport-water
mkdir 4-TravelPlaces\transport-air
mkdir 4-TravelPlaces\hotel
mkdir 4-TravelPlaces\time
mkdir 4-TravelPlaces\sky-weather
mkdir 5-Activities\event
mkdir 5-Activities\award-medal
mkdir 5-Activities\sport
mkdir 5-Activities\game
mkdir 6-Objects\sound
mkdir 6-Objects\music
mkdir 6-Objects\musical-instrument
mkdir 6-Objects\phone
mkdir 6-Objects\computer
mkdir 6-Objects\light-video
mkdir 6-Objects\book-paper
mkdir 6-Objects\money
mkdir 6-Objects\mail
mkdir 6-Objects\writing
mkdir 6-Objects\office
mkdir 6-Objects\lock
mkdir 6-Objects\tool
mkdir 6-Objects\other-object
mkdir 7-Symbols\transport-sign
mkdir 7-Symbols\warning
mkdir 7-Symbols\arrow
mkdir 7-Symbols\religion
mkdir 7-Symbols\zodiac
mkdir 7-Symbols\av-symbol
mkdir 7-Symbols\other-symbol
mkdir 7-Symbols\keycap
mkdir 7-Symbols\alphanum
mkdir 7-Symbols\geometric
mkdir 8-flags\flag
mkdir 8-flags\country-flag
mkdir 8-flags\subdivision-flag
mkdir z